models/contact.py
#from flask import flask_sqlalchemy
from utils.db import db

class Contact(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    fullname = db.Column(db.String(100))
    email = db.Column(db.String(100))
    phone = db.Column(db.String(100))

    def __init__(self, fullname, email, phone):
        self.fullname = fullname
        self.email = email
        self.phone = phone

app.py
from flask import Flask
from routes.contacts import contacts
from utils.db import db
from flask_sqlalchemy import SQLAlchemy
from config import DATABASE_CONNECTION_URI

app = Flask(__name__)

app.secret_key = "mySecretKey"
app.config['SQLALCHEMY_DATABASE_URI'] = DATABASE_CONNECTION_URI
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
db.init_app(app)

app.register_blueprint(contacts)

with app.app_context():
    db.create_all()

if __name__ == '__main__':
    app.run()

routes/contacts.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from utils.db import db
from models.contact import Contact

contacts = Blueprint('contacts', __name__)

@contacts.route('/', methods=['GET'])
def index():
    contacts_list = Contact.query.all()
    return render_template("index.html", contacts_list = contacts_list)

@contacts.route('/new', methods=['POST'])
def add_contact():
    fullname = request.form['fullname']
    email = request.form['email']
    phone = request.form['phone']
    new_contact = Contact(fullname, email, phone)
    db.session.add(new_contact)
    db.session.commit()
    flash(f"Contact {new_contact.fullname} added successfully!")
    return redirect(url_for('contacts.index'))
    #return redirect('/')
    #return f"Add a contact... \n{fullname}\n{email}\n{phone}"

@contacts.route('/update/<id>', methods=['POST', 'GET'])
def update(id):
    contact = Contact.query.get(id)
    if request.method == 'POST':
        contact.fullname = request.form['fullname']
        contact.email = request.form['email']
        contact.phone = request.form['phone']
        db.session.commit()
        flash(f"Contact {contact.fullname} updated successfully!")
        return redirect(url_for('contacts.index'))
    return render_template("update.html", contact = contact)

@contacts.route('/delete/<id>')
def delete(id):
    contact = Contact.query.get(id)
    db.session.delete(contact)
    db.session.commit()
    flash(f"Contact {contact.fullname} deleted successfully!")
    return redirect(url_for('contacts.index'))
    #return f"Delete a contact... {contact.fullname}"

@contacts.route('/about')
def about():
    return render_template("about.html")

templates/about.html
{% extends 'layout.html' %}
{% block content %}
<div class="text-light">
    <h1 class="fs-2 fw-light">About</h1>
    <p>About about about about about about ...</p>
</div>
{% endblock %}

templates/index.html
{% extends 'layout.html' %}

{% block content %}

<div class="row">
    <div class="col-md-4">
	{% include 'partials/_message.html' %}
	{% include 'partials/_contactForm.html' %} 
    </div>
    <div class="col-md-8">
	<div class="card mb-1 text-white bg-dark rounded-0">
	    {% include 'partials/_contactListTable.html' %}
	</div>
    </div>
</div>
{% endblock %}

templates/layout.html
<html>
    <head>
	<meta charset="UTF-8">
	<meta name="viewport" contect="width=device-width, initial-scale=1.0">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
	<link rel="stylesheet" href="{{ url_for('static', filename='/css/custom.css') }} "/>
	<title>RESTful API</title>
    </head>
    <body>
	<!--h1>Flask RESTful API</h1-->
	{% include('partials/_navbar.html') %}

	<div class="container p-2">
	    {% block content %}
	    {% endblock %}
	</div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    </body>
</html>

templates/partials/_about.html
{% extends 'layout.htlm' %}

{% block content %}
<div>
    <h2>About</h2>
    <p> About about about about about ...</p>
</div>

{% endblock %}

templates/partials/_contactForm.html
<form method="POST" action="/new" class="card bg-dark text-light rounded-0 ">
    <div class="card-body p-4"> 
        <div class="mb-3">
	    <label class="form-label">Full Name:</label>
            <input type="text" name="fullname" placeholder="Write your full name" class="form-control rounded-0 bg-dark border-0 text-white" />
    	</div>
    	<div class="mb-3">
	    <label for="exampleInputEmail1" class="form-label">Email address:</label>
	    <input type="email" name="email" placeholder="Write your email" class="form-control rounded-0 bg-dark border-0 text-white" />
    	</div>
        <div class="mb-3">
	    <label class="form-label">Phone:</label>
            <input type="text" name="phone" placeholder="Write your phone" class="form-control rounded-0 bg-dark border-0 text-white" />
        </div>
  
        <button type="submit" name="save" class="btn btn-primary rounded-0" value="Save">Save</button>
    </div>
</form>

templates/partials/_contactListTable.html
<div class="card-body table-responsive">
    <table class="table table-dark table-hover align-middle">
	<!--caption class="caption-top text-light">List of contacts</caption-->
	<thead>
	    <tr>
    	        <th scope="col">Full Name</th>
	    	<th scope="col">Email</th>
	    	<th scope="col">Phone</th>
	    	<th></th>
	    	<th></th>
	    </tr>
	</thead>
	<tbody class="table-group-divider">
            {% for contact in contacts_list %}
	    <tr>
	    	<td>{{ contact.fullname }}</td>
	    	<td>{{ contact.email }}</td>
	    	<td>{{ contact.phone }}</td>
	    	<td><a href="{{ url_for('contacts.update', id=contact.id) }}" class="btn btn-dark btn-sm bg-black rounded-0">Update</a></td>
	    	<td><a href="{{ url_for('contacts.delete', id=contact.id) }}" class="btn btn-danger btn-sm rounded-0">Delete</a></td>
	    </tr>
            {% endfor %}
	</tbody>
   </table>
</div>

templates/partials/_message.html
{% with messages = get_flashed_messages() %}
    {% if messages %}
        {% for message in messages %}
	<div class="alert alert-success alert-dismissible fade show rounded-0" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
    {% endif %}
{% endwith %}

templates/partials/_navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary bg-dark" data-bs-theme="dark">
  <div class="container">
    <a class="navbar-brand" href="/">Flask RESTful API</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a class="nav-link" href="/about">About</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

templates/update.html
{% extends 'layout.html' %}

{% block content %}

<div class="col-md-4 offset-md-4">
    <h1 class="text-light fs-3 fw-light text-center">Update Contact</h1>
    <form method="POST" action="/update/{{ contact.id }}" class="card bg-dark text-light rounded-0 ">
	<div class="card-body p-4"> 
            <div class="mb-3">
	        <label class="form-label">Full Name:</label>
                <input type="text" name="fullname" placeholder="Write your full name" class="form-control rounded-0 bg-dark border-0 text-white" value="{{ contact.fullname }}"/>
    	    </div>
    	    <div class="mb-3">
	    	<label for="exampleInputEmail1" class="form-label">Email address:</label>
	    	<input type="email" name="email" placeholder="Write your email" class="form-control rounded-0 bg-dark border-0 text-white" value="{{ contact.email }}"/>
    	    </div>
            <div class="mb-3">
	    	<label class="form-label">Phone:</label>
            	<input type="text" name="phone" placeholder="Write your phone" class="form-control rounded-0 bg-dark border-0 text-white" value="{{ contact.phone }}"/>
            </div>
  
        <button type="submit" name="save" class="btn btn-secondary rounded-0" value="Update">Update</button>
        </div>
    </form>
</div>

{% endblock %}